
[functions.send-booking-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/send-booking-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-booking-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-booking-confirmation/*.html" ]

[functions.get-booked-slots]
enabled = true
verify_jwt = true
import_map = "./functions/get-booked-slots/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-booked-slots/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-booked-slots/*.html" ]
